### ISSUE TITLE
XQuartz 2.8.0 alpha1 hangs on Big Sur

### ISSUE THREAD

**Issue by vgribov** [XQuartz/XQuartz#25]
Just have installed and it hangs on start. Logout, reboot - nothing helps. Running /Applications/Utilities/XQuartz.app/Contents/MacOS/X11.bin directly from terminal - also hangs without any output.

**Comment by vgribov** [comment]
```
$ ps ax | grep X11
 5627   ??  Ss     0:00.01 /opt/X11/libexec/privileged_startx -d /opt/X11/etc/X11/xinit/privileged_startx.d
 5812   ??  S      0:00.03 /Applications/Utilities/XQuartz.app/Contents/MacOS/X11.bin
 5818   ??  S      0:00.28 /Applications/Utilities/XQuartz.app/Contents/MacOS/X11.bin
 6328 s001  S+     0:00.00 grep X11
$ X

X.Org X Server 1.20.10
X Protocol Version 11, Revision 0
Build Operating System: Darwin 20.3.0 x86_64
Current Operating System: Darwin AERQ-MBP-05 20.2.0 Darwin Kernel Version 20.2.0: Wed Dec  2 20:39:59 PST 2020; root:xnu-7195.60.75~1/RELEASE_X86_64 x86_64
Build Date: 09 January 2021  04:06:30PM

Current version of pixman: 0.38.4
	Before reporting problems, check http://wiki.x.org
	to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
	(++) from command line, (!!) notice, (II) informational,
	(WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(==) Log file: "/Users/seva.gribov/.local/share/xorg/Xorg.0.log", Time: Mon Jan 11 17:24:24 2021
(==) Using default built-in configuration (21 lines)
(EE)
Fatal server error:
(EE) no screens found(EE)
(EE)
Please consult the The X.Org Foundation support
	 at http://wiki.x.org
 for help.
(EE) Please also check the log file at "/Users/seva.gribov/.local/share/xorg/Xorg.0.log" for additional information.
(EE)
(EE) Server terminated with error (1). Closing log file.
$ cat /Users/seva.gribov/.local/share/xorg/Xorg.0.log
[  1506.224]
X.Org X Server 1.20.10
X Protocol Version 11, Revision 0
[  1506.224] Build Operating System: Darwin 20.3.0 x86_64
[  1506.224] Current Operating System: Darwin AERQ-MBP-05 20.2.0 Darwin Kernel Version 20.2.0: Wed Dec  2 20:39:59 PST 2020; root:xnu-7195.60.75~1/RELEASE_X86_64 x86_64
[  1506.224] Build Date: 09 January 2021  04:06:30PM
[  1506.225]
[  1506.225] Current version of pixman: 0.38.4
[  1506.225] 	Before reporting problems, check http://wiki.x.org
	to make sure that you have the latest version.
[  1506.225] Markers: (--) probed, (**) from config file, (==) default setting,
	(++) from command line, (!!) notice, (II) informational,
	(WW) warning, (EE) error, (NI) not implemented, (??) unknown.
[  1506.225] (==) Log file: "/Users/seva.gribov/.local/share/xorg/Xorg.0.log", Time: Mon Jan 11 17:24:24 2021
[  1506.225] (II) Loader magic: 0x1038c7120
[  1506.225] (II) Module ABI versions:
[  1506.225] 	X.Org ANSI C Emulation: 0.4
[  1506.225] 	X.Org Video Driver: 24.1
[  1506.225] 	X.Org XInput driver : 24.1
[  1506.225] 	X.Org Server Extension : 10.0
[  1506.225] (==) Using default built-in configuration (21 lines)
[  1506.225] (==) --- Start of built-in configuration ---
[  1506.225] 	Section "Device"
[  1506.225] 		Identifier	"Builtin Default fbdev Device 0"
[  1506.225] 		Driver	"fbdev"
[  1506.225] 	EndSection
[  1506.225] 	Section "Screen"
[  1506.225] 		Identifier	"Builtin Default fbdev Screen 0"
[  1506.225] 		Device	"Builtin Default fbdev Device 0"
[  1506.225] 	EndSection
[  1506.225] 	Section "Device"
[  1506.225] 		Identifier	"Builtin Default vesa Device 0"
[  1506.225] 		Driver	"vesa"
[  1506.225] 	EndSection
[  1506.225] 	Section "Screen"
[  1506.225] 		Identifier	"Builtin Default vesa Screen 0"
[  1506.225] 		Device	"Builtin Default vesa Device 0"
[  1506.225] 	EndSection
[  1506.225] 	Section "ServerLayout"
[  1506.225] 		Identifier	"Builtin Default Layout"
[  1506.225] 		Screen	"Builtin Default fbdev Screen 0"
[  1506.225] 		Screen	"Builtin Default vesa Screen 0"
[  1506.225] 	EndSection
[  1506.225] (==) --- End of built-in configuration ---
[  1506.225] (==) ServerLayout "Builtin Default Layout"
[  1506.225] (**) |-->Screen "Builtin Default fbdev Screen 0" (0)
[  1506.225] (**) |   |-->Monitor "<default monitor>"
[  1506.225] (**) |   |-->Device "Builtin Default fbdev Device 0"
[  1506.225] (==) No monitor specified for screen "Builtin Default fbdev Screen 0".
	Using a default monitor configuration.
[  1506.225] (**) |-->Screen "Builtin Default vesa Screen 0" (1)
[  1506.225] (**) |   |-->Monitor "<default monitor>"
[  1506.226] (**) |   |-->Device "Builtin Default vesa Device 0"
[  1506.226] (==) No monitor specified for screen "Builtin Default vesa Screen 0".
	Using a default monitor configuration.
[  1506.226] (==) Not automatically adding devices
[  1506.226] (==) Not automatically enabling devices
[  1506.226] (==) Not automatically adding GPU devices
[  1506.226] (==) Max clients allowed: 256, resource mask: 0x1fffff
[  1506.226] (WW) `fonts.dir' not found (or not valid) in "/Library/Fonts".
[  1506.226] 	Entry deleted from font path.
[  1506.226] 	(Run 'mkfontdir' on "/Library/Fonts").
[  1506.226] (WW) `fonts.dir' not found (or not valid) in "/System/Library/Fonts".
[  1506.226] 	Entry deleted from font path.
[  1506.226] 	(Run 'mkfontdir' on "/System/Library/Fonts").
[  1506.226] (==) FontPath set to:
	/opt/X11/share/fonts/misc/,
	/opt/X11/share/fonts/TTF/,
	/opt/X11/share/fonts/OTF,
	/opt/X11/share/fonts/Type1/,
	/opt/X11/share/fonts/75dpi/:unscaled,
	/opt/X11/share/fonts/100dpi/:unscaled,
	/opt/X11/share/fonts/75dpi/,
	/opt/X11/share/fonts/100dpi/
[  1506.226] (==) ModulePath set to "/opt/X11/lib/xorg/modules"
[  1506.226] (==) |-->Input Device "<default pointer>"
[  1506.226] (==) |-->Input Device "<default keyboard>"
[  1506.226] (==) The core pointer device wasn't specified explicitly in the layout.
	Using the default mouse configuration.
[  1506.226] (==) The core keyboard device wasn't specified explicitly in the layout.
	Using the default keyboard configuration.
[  1506.226] (II) LoadModule: "fbdev"
[  1506.227] (WW) Warning, couldn't open module fbdev
[  1506.227] (EE) Failed to load module "fbdev" (module does not exist, 0)
[  1506.227] (II) LoadModule: "vesa"
[  1506.227] (WW) Warning, couldn't open module vesa
[  1506.227] (EE) Failed to load module "vesa" (module does not exist, 0)
[  1506.227] (II) LoadModule: "mouse"
[  1506.227] (WW) Warning, couldn't open module mouse
[  1506.227] (EE) Failed to load module "mouse" (module does not exist, 0)
[  1506.227] (II) LoadModule: "kbd"
[  1506.227] (WW) Warning, couldn't open module kbd
[  1506.227] (EE) Failed to load module "kbd" (module does not exist, 0)
[  1506.227] (EE) No drivers available.
[  1506.227] (EE)
Fatal server error:
[  1506.227] (EE) no screens found(EE)
[  1506.227] (EE)
Please consult the The X.Org Foundation support
	 at http://wiki.x.org
 for help.
[  1506.227] (EE) Please also check the log file at "/Users/seva.gribov/.local/share/xorg/Xorg.0.log" for additional information.
[  1506.227] (EE)
[  1506.228] (EE) Server terminated with error (1). Closing log file.
```

**Comment by dmk42** [comment]
I see this same behavior with alpha2 (same log file output as well).

**Comment by sparvu** [comment]
Does XQuartz run on Apple M1? Not talking here aobut the alpha 2 release, but the previous stable version ?

**Comment by dmk42** [comment]
@sparvu , yes, version 2.7.11 runs on an M1 system under Rosetta2.  An xterm and its shell run in x86_64 mode.  I am trying the alphas in hopes of getting a version of X that runs in native arm64 mode, though.

**Comment by sparvu** [comment]
@dmk42 :  cool. Will receive soon a M1 and I  really need XQuartz on that. Will try Rosetta2 until hopefully we could run it natively. Thanks a lot for heads up.

**Comment by satyrnhub** [comment]
this is fixed in alpha 4 for me, maybe try that?

**Comment by bpottier** [comment]
Alpha 4 is still failing to launch for me. Just bounces forever.

**Comment by satyrnhub** [comment]
> Alpha 4 is still failing to launch for me. Just bounces forever.

Might be a Big Sur thing, I'm using Catalina, and was having the same issue.

**Comment by dmk42** [comment]
Alpha 4 still fails for me as well (Big Sur, arm64).  The failure mode has not changed from Alpha 1.

**Comment by satyrnhub** [comment]
> Alpha 4 still fails for me as well (Big Sur, arm64). The failure mode has not changed from Alpha 1.

Well I don't know. I'm using a Catalina Hackintosh, so that probably makes a difference.

**Comment by jeremyhu** [comment]
alpha 1-3 didn't run the postinstall script due to me naming it incorrectly.  The postinstall script sets up the LaunchDaemon which should configure the directoris in /tmp with the correct ownership/permissions and build the font cache.  If that isn't done, it can lead to the issue reported here.

Running /opt/X11/bin/X runs the Xorg server not the XQuartz server.  That's not what you want ;)

I suggest installing alpha 4 and rebooting.  If that fixes the issue, great.  If not, please file a new ticket with relevant logging.

Note that alpha 3 and alpha 4 are not yet notarized due to an isuse preventing me from submitting for notarization which I'm trying to work through.
