### ISSUE TITLE
XQuartz 2.8.5beta3 bad rendering on window resize (missing exposes)

### ISSUE THREAD

**Issue by dpeterc** [XQuartz/XQuartz#309]
Starting with XQuartz 2.8.5beta3, complex applications no longer render correctly on resizing the windows.
It looks as if expose events are missing, so the application fails to redraw the newly shown area.
The following video shows the problem.
First we use nedit (available  pre-compiled in homebrew and package managers).
On resizing, the top menu is not rendered correctly, buttons are there and work, but were not drawn after resize.
Second application is color editor of ArahWeave, shows a more complex resize of color editor, where various widget components are not redrawn as they should be.
We use XQuartz 2.8.4 to demonstrate the correct behavior:

https://user-images.githubusercontent.com/15419249/210815143-e69d6aac-891a-4d8d-8e55-f09ba9f2c0f9.mp4

And this is XQuartz 2.8.5beta3 with incorrect rendering after resize:

https://user-images.githubusercontent.com/15419249/210815282-7900dfb9-ae83-40d2-9568-9de179a63900.mp4

**Comment by jeremyhu** [comment]
Where do I get that PANTONE app?

**Comment by dpeterc** [comment]
The PANTONE app is actually just a window within ArahWeave, color editor with PANTONE color library loaded by default.
You get it here as part of ArahWeave demo (PANTONE is included)
https://www.arahne.si/learn-support/software-demo/installing-arahweave-demo-on-mac-os-x-2/
To get the window from the video, open ArahWeave, select Fabric > Colors... menu.

If you don't like to install such a complex non standard application, you can use nedit, which is available from homebrew, macports or fink.
The problem with missing exposes is visible on menus which remain without title, after resizing the window to small size and back.

**Comment by jeremyhu** [comment]
The issue is addressed in beta4.

**Comment by dpeterc** [comment]
I have tested it on Xquartz 2.8.5.beta4 and the issue remains unsolved/unchanged, both on nedit as in ArahWeave.
I have tried both on Intel  Mac and on M1 Mac, both are Ventura.

**Comment by jeremyhu** [comment]
That's odd.  I'm definitely able to reproduce the issue with 2.8.5_beta4.  I bisected to determine where it regressed, and removed the offending change (something I thought was dead / unused code that actually wasn't).

Here's a simple build script to build the XQuartz server on top of the already installed XQuartz.  Just checkout `server-21.1-apple` or `master-apple` branches or `XQUartz-2.8.5_beta4` tag to get started.

[compile.sh](https://github.com/XQuartz/XQuartz/files/10378520/compile.sh.txt)

**Comment by jeremyhu** [comment]
Yeah, odd.  I didn't see it reproduce earlier today, but it is reproducing at https://github.com/XQuartz/xorg-server/commit/427a5b9ba5f21be3f02c0f6af33070f5316ca743 but not the previous commit.  I must be missing somewhere that needs this translation.

**Comment by jeremyhu** [comment]
Can you try the XQuartz.app I attached to https://github.com/XQuartz/XQuartz/issues/308#issuecomment-1376778273 ?

**Comment by dpeterc** [comment]
I have tried to compile Quartz as per instructions from above, but have failed since I use homebrew.
First it did not find autoreconf, but after supplying the full path it required configure.as ...
(autoreconf: error: 'configure.ac' is required)

So I gave up on this path.

Then I have also tried the binary XQuartz.app which you have attached. It appears to be only for Apple silicon and contains only the X server. I did not know how to apply it as a patch; it does not work stand-alone, can not be copied on top of existing XQuartz in Applications/Utilities. I don't know how to open .pkg file to replace single files and reinstall modified one.
Finally I tried to sudo copy contents to XQuartz.app to Applications/Utilities after which the system complained on some files. Strangely, XQuartz has disappeared from Applications/Utilities, but if I re-install it, it still works, I just don't know where it is. Maybe MacOS thinks I have been tampering with the system and is hiding that directory from me.

Anyhow I was unable to test it; can you provide a full .pkg of XQuartz, or a more detailed instructions on how to apply the patched XQuartz. Sorry for being such a noob on Mac.

**Comment by jeremyhu** [comment]
Xorg moved away from autoconf to using meson for the server.  The script I provided doesn't really need MacPorts.  It just needs meson.

You can also build the required tools by running [install-or-update-macports.sh](https://github.com/XQuartz/XQuartz/blob/main/install-or-update-macports.sh), but it takes a little while.

**Comment by jeremyhu** [comment]
Here's XQuartz.app with the latest changes built for x86_64.  Just replace your Applications/Utilities/XQuartz.app with this one.
[XQuartz.app.tar.gz](https://github.com/XQuartz/XQuartz/files/10390287/XQuartz.app.tar.gz)

eg:

    cd /Applications/Utilities
    sudo tar cjf ~/XQuartz.bak.tar.bz2 XQuartz.app
    sudo rm -rf XQuartz.app
    sudo tar xzf ~/Downloads/XQuartz.app.tar.gz

**Comment by dpeterc** [comment]
Thank you; using these instructions I was able to install it.
And I confirm that with this version, window resize works correctly, and widgets repaint to correct new size.
Thanks for taking the time to investigate this matter; without this fix, it would not be usable for me or my customers.

**Comment by jeremyhu** [comment]
Great.  I'll get this out in another beta soon.
