### ISSUE TITLE
OSX 15.0: Ctrl-enter is broken again

### ISSUE THREAD

**Issue by sirainen** [XQuartz/XQuartz#409]
This was fixed in https://github.com/XQuartz/XQuartz/issues/394 for OSX 14.5, but it's broken again in 15.0.

**Comment by raoultrines** [comment]
Just upgraded to OSX 15.1, and yes, Ctrl-enter is broken for me as well.

**Comment by jeremyhu** [comment]
Should be working again in the latest 15.2 betas.

**Comment by raoultrines** [comment]
@jeremyhu I just upgraded to MacOS 15.2, and Ctrl-Enter is still broken. Somehow that fix for 14.5 never seems to make it into the 15.x mainline.

**Comment by jeremyhu** [comment]
Hmm.  That is true that it didn't get picked up in 15.0, but it looked like it ahould be there in 15.2 (in 24C83 and later versions).  I can take a closer look later...

**Comment by jeremyhu** [comment]
Ok, that's quite unexpected as the relevant code change that fixed this the first time does appear to be present in 15.2 (24C101), so either something was misunderstood about this change or something else broke this behavior in a similar way since the fix landed... =/

Could you please file a new feedback report, and I'll get that new one routed (it's easier / cleaner to have new reports which are related to old ones than to just re-open previous ones).

**Comment by raoultrines** [comment]
Just submitted a new feedback report, FB16331190.

**Comment by raoultrines** [comment]
Just upgraded to MacOS 15.3 (24D60). Shift-, Command-, Option-Enter work fine. With Ctrl-Enter, I found something very weird. I have an external keyboard attached to my Mac, and if I press Ctrl-Enter with both keys on the same keyboard, it does not work. But if I press Ctrl-Enter with Ctrl on one keyboard and Enter on the other (does not matter which way around), then it does work! Strange...

Also, if I remove the external keyboard, then Ctrl-Enter does not work on the internal keyboard either.

**Comment by robohack** [comment]
This is from macOS 15.2, on an Intel Mac, with a Magic Keyboard (0x026c with 8.70 firmware), and I'm running XQuartz 2.8.5 (xorg-server 21.1.6), so not a problem here for me:


```
KeyPress event, serial 34, synthetic NO, window 0x8000001,
    root 0x140, subw 0x0, time 3448406598, (160,81), root:(1675,449),
    state 0x0, keycode 70 (keysym 0xffe4, Control_R), same_screen YES,
    XLookupString gives 0 bytes: 
    XmbLookupString gives 0 bytes: 
    XFilterEvent returns: False

KeyPress event, serial 37, synthetic NO, window 0x8000001,
    root 0x140, subw 0x0, time 3448407581, (160,81), root:(1675,449),
    state 0x4, keycode 44 (keysym 0xff0d, Return), same_screen YES,
"   XLookupString gives 1 bytes: (0d) "
"   XmbLookupString gives 1 bytes: (0d) "
    XFilterEvent returns: False

KeyRelease event, serial 37, synthetic NO, window 0x8000001,
    root 0x140, subw 0x0, time 3448407725, (160,81), root:(1675,449),
    state 0x4, keycode 44 (keysym 0xff0d, Return), same_screen YES,
"   XLookupString gives 1 bytes: (0d) "
    XFilterEvent returns: False

KeyRelease event, serial 37, synthetic NO, window 0x8000001,
    root 0x140, subw 0x0, time 3448408038, (160,81), root:(1675,449),
    state 0x4, keycode 70 (keysym 0xffe4, Control_R), same_screen YES,
    XLookupString gives 0 bytes: 
    XFilterEvent returns: False

KeyPress event, serial 37, synthetic NO, window 0x8000001,
    root 0x140, subw 0x0, time 3448417357, (160,81), root:(1675,449),
    state 0x0, keycode 67 (keysym 0xffe3, Control_L), same_screen YES,
    XLookupString gives 0 bytes: 
    XmbLookupString gives 0 bytes: 
    XFilterEvent returns: False

KeyPress event, serial 37, synthetic NO, window 0x8000001,
    root 0x140, subw 0x0, time 3448417997, (160,81), root:(1675,449),
    state 0x4, keycode 44 (keysym 0xff0d, Return), same_screen YES,
"   XLookupString gives 1 bytes: (0d) "
"   XmbLookupString gives 1 bytes: (0d) "
    XFilterEvent returns: False

KeyRelease event, serial 37, synthetic NO, window 0x8000001,
    root 0x140, subw 0x0, time 3448418085, (160,81), root:(1675,449),
    state 0x4, keycode 44 (keysym 0xff0d, Return), same_screen YES,
"   XLookupString gives 1 bytes: (0d) "
    XFilterEvent returns: False

KeyRelease event, serial 37, synthetic NO, window 0x8000001,
    root 0x140, subw 0x0, time 3448418477, (160,81), root:(1675,449),
    state 0x4, keycode 67 (keysym 0xffe3, Control_L), same_screen YES,
    XLookupString gives 0 bytes: 
    XFilterEvent returns: False
```

**Comment by sirainen** [comment]
Just upgraded to 10.3, and ctrl-enter seems to work again for me.
